# Generated by Django 2.0.7 on 2018-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(height_field=50, upload_to='Posts', width_field=50),
        ),
    ]
