# Generated by Django 2.0.7 on 2018-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20181008_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='Posts'),
        ),
    ]
