# Generated by Django 2.0.7 on 2018-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20181010_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='Posts'),
        ),
    ]
