# Generated by Django 2.0.7 on 2018-10-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20181010_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='Posts'),
        ),
    ]
