# Generated by Django 2.0.7 on 2018-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20181010_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
