# Generated by Django 2.0.7 on 2018-10-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20181011_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='image',
        ),
    ]
